CONFIG = {
    "id": "sim-demo",
    "label": "Simulated demo",
    "http": {"host": "127.0.0.1", "port": 18083},
    "capacity_wh": 1280,
    "cost_model": "solar-zero",
    "narrative_html": "<p>Hardware-free telemetry demo.</p>",
    "channel_priority": {},
    "mode_channels": {
        "main": ["load.w"],
        "ups": ["ups.soc_pct", "ups.power_w"],
    },
    "sources": [
        {
            "id": "main_sim",
            "kind": "simulated",
            "role": "main",
            "reconnect_delay": 5,
            "stale_after_s": 3,
            "capabilities": {"solar_measured": True},
            "values": {"battery.soc_pct": 87, "solar.input_w": 40, "load.w": 12},
            "interval": 1,
            "emit_for": 15,
        },
        {
            "id": "ups_sim",
            "kind": "simulated",
            "role": "ups",
            "reconnect_delay": 5,
            "stale_after_s": 3,
            "capabilities": {"solar_measured": False},
            "values": {"ups.soc_pct": 95, "ups.voltage_v": 12.2},
            "interval": 1,
            "emit_for": None,
        },
    ],
}
